ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<int:i>',views.addtocart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('cartremove/<int:i>',views.cartremove,name="cartremove"),
    path('cartfullremove/<int:i>',views.cartfullremove,name="cartfullremove"),
    path('orderform',views.orderform,name="orderform"),
    path('status<str:p>',views.paymentstatus,name="status"),
    path('orderview',views.orderview,name="orderview"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
    path('',views.searchproducts,name="search"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [
    path('',views.categories,name="category"),
    path('product/<int:i>',views.products,name="product"),
    path('detail/<int:i>', views.productdetail, name="detail"),
    path('register',views.register,name='register'),
    path('login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout'),
    path('addcategories',views.add_categories,name='addcategories'),
    path('addproducts',views.add_products,name='addproducts'),
    path('addstock/<int:i>',views.addstock,name='addstock'),

]

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product

# Create your views here.
from django.db.models import Q
def searchproducts(request):
    p = None
    query = ""
    if (request.method == "POST"):  # after form submission
        query = request.POST['q']
        print(query)
        if query:
            p = Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))  # django lookups

    return render(request, 'search.html', context={'pro': p, 'query': query})

ecommerce/templates/addcategories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<div class="container mt-5 p-3 bg-success" style="margin-bottom:100px;">
<h2>Add Category Details</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-3">
  <label class="form-label">Category name</label>
  <input type="text" class="form-control" name="n" placeholder="Enter Category">
</div>
    <div class="mb-3">
  <label class="form-label">Image</label>
  <input type="file" class="form-control"  name="i">
</div>
    <div class="mb-3">
  <label class="form-label">Description</label>
  <textarea class="form-control" name="d"></textarea>
</div>
    <div class="mb-3 text-center">
    <input type="submit" class="btn btn-dark text-light px-4">
  </div>
</form>
    </div>
</center>
{% endblock %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->

ecommerce/templates/addproducts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<div class="container mt-5 p-3 bg-success" style="margin-bottom:100px;">
<h2>Add Product Details</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Category name</label>
        <div class="form-group">
            <select class="custom-select" name="c">
                {% for i in links %}
                <option value="{{i.name}}">{{i.name}}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="mb-3">
  <label class="form-label">Product name</label>
  <input type="text" class="form-control" name="n" placeholder="Enter Product">
</div>
    <div class="mb-3">
  <label class="form-label">Image</label>
  <input type="file" class="form-control"  name="i">
</div>
    <div class="mb-3">
  <label class="form-label">Description</label>
  <textarea class="form-control" name="d"></textarea>
</div>
    <div class="mb-3">
  <label class="form-label">Price</label>
  <input type="number" class="form-control" name="p" placeholder="Enter Price">
</div>
    <div class="mb-3">
  <label class="form-label">Stock</label>
  <input type="number" class="form-control" name="s" placeholder="Enter Stock">
</div>
    <div class="mb-3 text-center">
    <input type="submit" class="btn btn-dark text-light px-4">
  </div>

</form>
    </div>
</center>
{% endblock %}

ecommerce/templates/addstock.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 p-3 bg-success" style="margin-bottom:100px;">
<h1 class="text-center">Edit Book Details</h1>
<form method="POST">
    {% csrf_token %}

    <div class="mb-3">
  <label class="form-label">Stock</label>
  <input type="number" class="form-control" name="s" value="{{pro.stock}}" placeholder="Enter new stock">
</div>
    <div class="mb-3 text-center">
    <input type="submit" class="btn btn-dark text-light px-4">
  </div>
</form>
    </div>

{% endblock %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->

ecommerce/templates/addtocart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 p-3 bg-success" style="margin-bottom:100px;">
    <h2 class="text-center">Shopping Cart</h2>
    <div class="cart-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="table-main table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Images</th>
                                    <th>Product Name</th>
                                    <th>Unit Price</th>
                                    <th>Quantity</th>
                                    <th>Sub Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for i in cart %}
                                <tr style="background-color:#c2f0c2;">
                                    <td >
                                        <a href="#">
									<img src="{{i.product.image.url}}" height="200px" width="100px" class="img-thumbnail p-1" alt="" />
								</a>
                                    </td>
                                    <td class="name-pr">
                                        <a href="#">
									{{i.product.name}}
								</a>
                                    </td>
                                    <td class="price-pr text-dark">
                                        <p>{{i.product.price}}</p>
                                    </td>
                                    <td class="quantity-box"><input type="number" size="4" value="{{i.quantity}}" min="0" step="1" class="c-input-text qty text"></td>
                                    <td class="total-pr text-dark">
                                        <p>{{i.subtotal}}</p>
                                    </td>

                                    <td>
                                        {% if i.product.stock > 0 %}
                                        <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa fa-plus-circle text-danger" aria-hidden="true"></i></a>
                                        <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa fa-minus-circle text-danger" aria-hidden="true"></i></a>
                                        <a href="{% url 'cart:cartfullremove' i.product.id %}"><i class="fa fa-trash text-danger" aria-hidden="true"></i></a>
                                        {% else %}
                                        <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa fa-minus-circle text-danger" aria-hidden="true"></i></a>
                                        <a href="{% url 'cart:cartfullremove' i.product.id %}"><i class="fa fa-trash text-danger" aria-hidden="true"></i></a>
                                        {% endif %}
                                    </td>
                                </tr>
                                <tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            <div class="col-lg-4">
                    <div class="table-main table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="text-center">Checkout</th>

                                </tr>
                            </thead>
                            <tbody>
                                <tr style="background-color:#c2f0c2;">
                                    <td class="text-center" >
                                        Total:<span class="text-dark">{{total}}</span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-between">
                       <a href="{% url 'cart:orderform' %}" class="btn btn-secondary">Place Order</a>
                       <a href="{% url 'shop:category' %}" class="btn btn-secondary">Continue Shopping</a>
    </div>
                    </div>
                </div>
            </div>



            <div>

        </div>

            <div class="row my-5">
                <div class="col-lg-6 col-sm-6">
                    <div class="coupon-box">
                        <div class="input-group input-group-sm">
                            <input class="form-control" placeholder="Enter your coupon code" aria-label="Coupon code" type="text">
                            <div class="input-group-append">
                                <button class="btn btn-theme" type="button">Apply Coupon</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <div class="update-box">
                        <input value="Update Cart" type="submit">
                    </div>
                </div>
            </div></div>
        </div></div>
            <div>
            </div>


{% endblock %}

<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 p-3 bg-success text-light" style="margin-bottom:100px;">
<h1 class="text-center text-light">Login</h1>
<form method="POST">
    {% csrf_token %}

    <div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter username">
</div>
    <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control"  name="p" placeholder="Enter password">
</div>
    <div class="mb-3 text-center">
    <input type="submit" class="btn btn-dark text-light px-4">
  </div>
</form>
    </div>
{% endblock %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<div class="container mt-5 p-3 text-dark" style="margin-bottom:100px;background-color:#99ff99">

<h1 class="text-center text-dark">Customer Name: {{user.first_name}}</h1>
        {% for i in orders %}
    <div class="about-box-main mt-2">
        <div class="container">
            <div class="row">
                <div class="col-lg-1">
                    </div>
				<div class="col-lg-4 bg-secondary">
                    <div class="banner-frame mt-2"> <img height="300px" width="60%" src="{{i.product.image.url}}" alt="" />
                    </div>
                </div>
                <div class="col-lg-7">
                    <h2><span style="color:#b0b435">Product name:</span><b>{{i.product.name}}</b></h2>
                    <p><span style="color:#b0b435">Price:</span><b>{{i.product.price}}</b></p>
                    <p><span style="color:#b0b435">No: of items:</span><b>{{i.no_of_items}}</b></p>
                    <p><span style="color:#b0b435">Order id:</span><b>{{i.order_id}}</b></p>
                    <p><span style="color:#b0b435">Ordered on:</span><b>{{i.ordered_date}}</b></p>
                    <p><span style="color:#b0b435">Deliver Status:</span><b>{{i.delivery_status}}</b></p>

                </div>
            </div>
            </div></div>{% endfor %}

</div>
</center>
    {% endblock %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 p-3 bg-success text-light" style="margin-bottom:100px;">
<h1 class="text-center text-light">Payment</h1>
    <center>
    <form action="{% url 'cart:status' name %}" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_7MBIFnOwDq442U" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{payment.id}}" "// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="SmartShop"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{name}}"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="gray"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>

        </center>
    </div>
{% endblock %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->

ecommerce/templates/paymentstatus.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 p-3 bg-success text-light" style="margin-bottom:100px;">
<h1 class="text-center text-light">Payment successful</h1>
</div>
{% endblock %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->

ecommerce/templates/placeorder.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5 p-3 bg-success text-light" style="margin-bottom:100px;">
    <h2 class="text-center text-light">Billing Details</h2>
    <form method="POST">
    {% csrf_token %}

    <div class="mb-3">
  <label class="form-label">Address</label>
        <textarea class="form-control" name="a">Write address here</textarea>
</div>
    <div class="mb-3">
  <label class="form-label">Phone</label>
  <input type="number" class="form-control"  name="p" placeholder="Enter phone number">
</div>
        <div class="mb-3">
  <label class="form-label">Pin</label>
  <input type="number" class="form-control"  name="pi" placeholder="Enter pin number">
</div>
    <div class="mb-3 text-center">
    <input type="submit" class="btn btn-dark text-light px-4">
  </div>
</form>
</div>


{% endblock %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->

ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-5 ms-0">
    <img src="{{cat.image.url}}" height="500px" width="100%">

</div>
<div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>{{cat.name}}</h1>
                        <p>{{cat.desc}}</p>
                    </div>
                </div>
            </div>
           <div class="row special-list">
               {% for i in pro %}
                <div class="col-lg-3 col-md-6 special-grid best-seller">
                    <div class="products-single fix">
                        <div class="box-img-hover">
                            <div class="type-lb">
                                <p class="sale">Sale</p>
                            </div>
                            <img src="{{i.image.url}}" height="300px" width="100%" alt="Image">
                            <div class="mask-icon">

                                <a class="cart" href="{% url 'shop:detail' i.id %}">Details</a>
                            </div>
                        </div>
                        <div class="why-text">
                            <h4>{{i.name}}</h4>
                            <h5>{{i.price}}</h5>
                        </div>
                    </div>
                </div>
{% endfor %}
<!--                <div class="col-lg-3 col-md-6 special-grid top-featured">-->
<!--                    <div class="products-single fix">-->
<!--                        <div class="box-img-hover">-->
<!--                            <div class="type-lb">-->
<!--                                <p class="new">New</p>-->
<!--                            </div>-->
<!--                            <img src="images/img-pro-02.jpg" class="img-fluid" alt="Image">-->
<!--                            <div class="mask-icon">-->
<!--                                <ul>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>-->
<!--                                </ul>-->
<!--                                <a class="cart" href="#">Add to Cart</a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="why-text">-->
<!--                            <h4>Lorem ipsum dolor sit amet</h4>-->
<!--                            <h5> $9.79</h5>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

<!--                <div class="col-lg-3 col-md-6 special-grid top-featured">-->
<!--                    <div class="products-single fix">-->
<!--                        <div class="box-img-hover">-->
<!--                            <div class="type-lb">-->
<!--                                <p class="sale">Sale</p>-->
<!--                            </div>-->
<!--                            <img src="images/img-pro-03.jpg" class="img-fluid" alt="Image">-->
<!--                            <div class="mask-icon">-->
<!--                                <ul>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>-->
<!--                                </ul>-->
<!--                                <a class="cart" href="#">Add to Cart</a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="why-text">-->
<!--                            <h4>Lorem ipsum dolor sit amet</h4>-->
<!--                            <h5> $10.79</h5>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

<!--                <div class="col-lg-3 col-md-6 special-grid best-seller">-->
<!--                    <div class="products-single fix">-->
<!--                        <div class="box-img-hover">-->
<!--                            <div class="type-lb">-->
<!--                                <p class="sale">Sale</p>-->
<!--                            </div>-->
<!--                            <img src="images/img-pro-04.jpg" class="img-fluid" alt="Image">-->
<!--                            <div class="mask-icon">-->
<!--                                <ul>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>-->
<!--                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>-->
<!--                                </ul>-->
<!--                                <a class="cart" href="#">Add to Cart</a>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="why-text">-->
<!--                            <h4>Lorem ipsum dolor sit amet</h4>-->
<!--                            <h5> $15.79</h5>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
            </div>
        </div>
    </div>
    <!-- End Products  -->
{% endblock %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 p-3 bg-success text-light" style="margin-bottom:100px;">
<h1 class="text-center text-light">Register</h1>
<form method="POST">
    {% csrf_token %}

    <div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u"  placeholder="Enter username">
</div>
    <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control"  name="p"  placeholder="Enter password">
</div>
    <div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="Confirm password">
</div>
    <div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="email" class="form-control" name="e" placeholder="Enter email">
</div>
    <div class="mb-3">
  <label  class="form-label">First name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter first name">
</div>
    <div class="mb-3">
  <label  class="form-label">Last name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter last name">
</div>
    <div class="mb-3 text-center">
    <button type="submit" class="btn btn-dark text-light px-4">Register</button>
  </div>
</form>
</div>
{% endblock %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    {% if pro == None %}
<div class="container mt-5 p-3 bg-success text-dark" style="margin-bottom:100px;">

<h1 class="text-center text-dark">Search Products</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <input type="text" class="form-control" name="q">
            <input type="submit" class="btn btn-secondary">
        </div>
    </form>
    </div>
    {% else %}

    <div class="row special-list">
        {% for i in pro %}
        <div class="col-lg-3 col-md-6 special-grid best-seller">
            <div class="products-single fix">
                <div class="box-img-hover">
                    <div class="type-lb">
                        <p class="sale"></p>
                    </div>
                    <img src="{{i.image.url}}" class="img-fluid" alt="Image">
                    <div class="mask-icon">
                        <a class="cart" href="{% url 'shop:detail' i.id %}">Details</a>
                    </div>


                </div>

            <div class="why-text">
                <h4>{{i.name}}</h4>
                <h5>{{i.price}}</h5>
            </div>
            </div>
        </div>

    {% empty %}

    <h2 class="text-center text-light">No Results Found</h2>

    {% endfor %}
    </div>

{% endif %}
</center>
{% endblock %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->